added prompts for update products and complete order to ui.js
Funky-Chickens/Bangazon-CLI pull request #17
Opened 2017-09-26 19:59 UTC by cait-rocco

I made the following changes:

updated the menu and added prompts for update product and complete order to ui.js.

To test:

currently not testable until functionality exist to activate a user. when available, try each menu option and see that it prompts you for the correct info. no functionality in yet to add the user entered items to the database.

2017-09-26 20:23 UTC, mozecode commented on app/ui.js
> +  ${magenta('**  Your order total is,' total, 'Ready to purchase (Y/N)  **')}`);
Hey, take a look at this line-- comma after is needs to be moved outside of the quotes.

2017-09-26 20:28 UTC, mozecode commented on app/ui.js
> +let completeOrderPrompt = () => {
Change the name of this and where it's called-- I keep getting this error: Identifier 'completeOrderPrompt' has already been declared

2017-09-27 14:31 UTC, Rian501 commented on app/ui.js
> +  console.log('Your order total is,' total, 'Ready to purchase (Y/N)  **');
This comma needs to be outside the quote marks plz

2017-09-27 14:32 UTC, Rian501 requested changes
With that one comma change, it seems to be working insofar as I am able to test it!

2017-09-27 14:35 UTC, merged